export const INITIALIZE_DATA = 'INITIALIZE_DATA'
export const SET_DATA = 'SET_DATA'
export const SET_EDITOR_USER_MODE = 'SET_EDITOR_USER_MODE'
export const GET_EDITOR_USER_MODE = 'GET_EDITOR_USER_MODE'